
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: "FEVR - Frontenders Verona - Eventi e formazione frontend javascript Verona"
subtitle: "Eventi e formazione frontend javascript Verona"
description: "Eventi e formazione frontend javascript Verona"
logo: "/img/logo2016.png"
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "http://www.fevr.it" # the base hostname & protocol for your site
baseurl: ""

permalink: "/:categories/:year/:month/:title/"

twitter:
  username: "__fevr"

social:
  name: "FEVR"
  links:
    - "https://twitter.com/__fevr"
    - "https://www.facebook.com/groups/frontendersverona/"
    - "http://www.eventbrite.it/o/fevr-7297766259"
    - "https://www.youtube.com/channel/UCyBgo76Z93uqEXqK6GmxN5w"
    - "https://speakerdeck.com/fevr"
    - "https://github.com/fevrcoding"

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Google analytics
ga_tracking_id: "UA-3216603-10"

# Category descriptions (for archive pages)
descriptions:
  - cat: eventi
    desc: "I nostri eventi."

sponsor:
  - name: "Graffiti HUB"
    img: "img/sponsor/graffitihub.png"
    url: "https://www.facebook.com/GraffitiHub/"

  - name: "Kaleidoscope Studio"
    img: "img/sponsor/kaleidoscope.png"
    url: "http://www.kaleidoscope.it/"

  - name: "JetBrains"
    img: "img/sponsor/jetbrains.png"
    url: "https://www.jetbrains.com/"

  - name: "O'Reilly"
    img: "img/sponsor/oreilly.png"
    url: "http://www.oreilly.com/"

  - name: "Plural Sight"
    img: "img/sponsor/pluralsight.png"
    url: "https://www.pluralsight.com/"

  - name: "Avocode"
    img: "img/sponsor/avocode.png"
    url: "https://avocode.com/"


social:
  email: "fevr.gruppo@gmail.com"
  facebook:
    user: "frontendersverona"
    url: "https://www.facebook.com/groups/frontendersverona/"
  twitter:
    user: "__fevr"
    url: "https://twitter.com/__fevr"
  slack:
    url: "http://fevr.herokuapp.com/"
  eventbrite:
    url: "http://www.eventbrite.it/o/fevr-7297766259"
  youtube:
    url: "https://www.youtube.com/channel/UCyBgo76Z93uqEXqK6GmxN5w"
  speakerdeck:
    url: "https://speakerdeck.com/fevr"
  meetup:
    url: "https://meetup.com/it-IT/FEVR-Frontenders-Verona/"

team:
  - name: "Matteo Guidotto"
    role: "Project Manager"
    img: "img/matteo.jpg"
    social:
      - name: Facebook
        url: "https://www.facebook.com/matteoguidotto"
        icon: fa-facebook

      - name: Twitter
        url: "https://twitter.com/j8matteo"
        icon: fa-twitter

      - name: SlideShare
        url: "http://www.slideshare.net/matteoguidotto"
        icon: fa-slideshare

      - name: LinkedIn
        url: "https://www.linkedin.com/in/matteoguidotto"
        icon: fa-linkedin

  - name: "Marco Solazzi"
    role: "Senior Frontend Developer"
    img: "img/marco.jpg"
    social:
      - name: Facebook
        url: "https://www.facebook.com/dwightjack"
        icon: fa-facebook

      - name: Twitter
        url: "https://twitter.com/dwightjack"
        icon: fa-twitter

      - name: Github
        url: "https://github.com/dwightjack"
        icon: fa-github

      - name: LinkedIn
        url: "https://www.linkedin.com/in/marcosolazzi"
        icon: fa-linkedin

  - name: "Matteo Ronchi"
    role: "Senior Software Engineer"
    img: "img/matteo-ronchi.jpg"
    social:
      - name: Facebook
        url: "https://www.facebook.com/matteo.ronchi.979"
        icon: fa-facebook

      - name: Twitter
        url: "https://twitter.com/cef62"
        icon: fa-twitter

      - name: Github
        url: "https://github.com/cef62"
        icon: fa-github

      - name: LinkedIn
        url: "https://www.linkedin.com/in/matteoronchi"
        icon: fa-linkedin


  - name: "Luca Maroni"
    role: "Frontend Developer"
    img: "img/luca-maroni.jpg"
    social:
      - name: Facebook
        url: "https://www.facebook.com/lucakinomaroni"
        icon: fa-facebook

      - name: Twitter
        url: "https://twitter.com/lucakinomaroni"
        icon: fa-twitter

      - name: Github
        url: "https://github.com/kino90"
        icon: fa-github

      - name: LinkedIn
        url: "https://www.linkedin.com/in/lucakinomaroni"
        icon: fa-linkedin

defaults:
  - scope:
      path: ""
    values:
      title: "FEVR - Frontenders Verona - Eventi e formazione frontend javascript Verona"
      subtitle: "Eventi e formazione frontend javascript Verona"
      image: /img/logo2016.png
